### ISSUE TITLE
Make initial setup for NimGui easier

### ISSUE THREAD

**Issue by psuong** [InitialPrefabs/nimgui#2]
# TODO

* Add in a warning or error to the setup wizard when
  * [x] When the user has URP, but did not define `URP_ENABLED` into the scripting define
  * [x] Double check that the error message is obvious or that NimGui early outs before trying to execute logic with an improper setup
* [x] Pack in the Renderer assets so that it's easier to test when importing the package (maybe as an alternative, automatically assign the correct renderer asset if the `Demo` scene is running)
* Update
  * [x] Documentation PDF
  * [x] [Documentation Site](https://nimgui.initialprefabs.com/index.html)
  * [x] Package version
* [x] Test with 2020.3 LTS
* [x] Test with 2021.2
* [x] Published to Asset Store
* [x] Redeploy demo to itch
* [x] Published to itch.io
* [x] Update CHANGELOG in nimgui repo.

**Comment by psuong** [comment]
I've added a window that is "reactive" to which render pipeline you are using.

# URP

## `URP_ENABLED` defined, but missing `ImGuiRenderFeature`
If you defined `URP_ENABLED` in your Scripting Defines but are missing the `ImGuiRenderFeature` in your ForwardRenderer, then the **RenderPipeline Setup** section will display the following error. Clicking the **Fix now** button will add the `ImGuiRenderFeature` to all of your ForwardRenderers' Render Features list.

![image](https://user-images.githubusercontent.com/9100688/161431191-e531a339-4a15-4849-9ed9-a10479ff7c7b.png)

## `URP_ENABLED` defined, but missing URP Asset in your Graphics Settings
If you defined `URP_ENABLED`, but forgot to add the RenderPipeline Asset to your graphics settings, the following error will be displayed.

> You **must** add the RenderPipeline Asset to your GraphicSetting's Scriptable Render Pipeline Settings field!

![image](https://user-images.githubusercontent.com/9100688/161431463-a67dcb57-21db-4de4-9572-302aa81dd3f5.png)

## You're using Builtin RenderPipeline
When using BuiltinRenderPipeline, you will need to setup the camera in code by calling `DefaultImGuiInitialization.SetupCamera(camera, CameraEvent)`. There is no asset setup you need to do directly in your project.

![image](https://user-images.githubusercontent.com/9100688/161431479-25271906-3d86-4a7a-9801-a457835b6c15.png)

**Comment by psuong** [comment]
Here are the following error messages that will display in the console depending on the situation of the error message.
```
"[ERROR] The SDF shader is missing, please make sure all assets from NimGui are imported and that the SDF shader is in the Always Included Shader settings.",
"[ERROR] You have enabled URP in NimGui, but have not assigned the Scriptable Render Pipeline Settings in your Project.",
"[ERROR] Your Pipeline Asset is missing the ImGuiRenderFeaturePass.",
"[ERROR] Please make sure that you imported the UbuntuMono-Regular_Atlas.png, this is the default fallback texture.",
"[ERROR] Please make sure that you imported the UbuntuMono-Regular_Glyphs.asset, this is the default fallback font data."
```

If NimGui catches one of these cases, then NimGui will **pause** the editor so you can review the errors and do the appropriate step to fix them. Again this is an **Editor only** feature.

**Comment by psuong** [comment]
Warning message for when the SDF shader is not included in the build.

![image](https://user-images.githubusercontent.com/9100688/161441433-d3d0c151-786f-4ec7-a388-0a9f4b3adbea.png)

**Comment by psuong** [comment]
NimGui 1.0.1 is released on itch & Unity Asset Store.
