### ISSUE TITLE
Upgrade Collections package to 1.3.1

### ISSUE THREAD

**Issue by psuong** [InitialPrefabs/nimgui#6]
With DOTS 0.51 out, the collections package renames UnsafeHashMap to UnsafeParallelHashMap. 

# TODO
* [x] Update package dependency
* [x] Update outstanding documentation (web)
* [x] Update outstanding documentation (pdf)
* [x] Add upgrade notes to Asset Store
* [x] Approved on Asset Store

**Comment by psuong** [comment]
Asset store has been updated here: https://assetstore.unity.com/packages/tools/gui/nimgui-a-1-draw-call-ui-209126
